
services:
  cbsplit:
    image: ${IMAGE_NAME}:cbsplit
    build:
      context: flavours/cbsplit
      additional_contexts:
        shared: shared
      target: base

  cbsplit-dev:
    image: ${IMAGE_NAME}:cbsplit-dev
    build:
      context: flavours/cbsplit
      additional_contexts:
        shared: shared
      target: dev

  ltv:
    image: ${IMAGE_NAME}:ltv
    build:
      context: flavours/ltv
      additional_contexts:
        shared: shared
      target: base

  ltv-dev:
    image: ${IMAGE_NAME}:ltv-dev
    build:
      context: flavours/ltv
      additional_contexts:
        shared: shared
      target: dev

